version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${DB_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8080:${ADMINER_PORT}
    environment:
      ADMINER_DEFAULT_SERVER: ${ADMINER_DEFAULT_SERVER}
      ADMINER_DESIGN: ${ADMINER_DESIGN}
    networks:
      - default
    depends_on:
      postgres:
        condition: service_healthy

  maildev:
    container_name: maildev
    image: maildev/maildev
    restart: unless-stopped
    ports:
      - 1025:${SMTP_PORT}
      - 1080:1080
    networks:
      - default

networks:
  default:
    name: ${NETWORK_NAME}

volumes:
  postgres_data:
    name: postgres_data
